(async()=>{
const names=['tl_act_plate','tl_bezel','tl_track_enemy','tl_track_party','tl_divider','tl_act_zone','tl_pointer','tl_hub','tl_marker_party','tl_marker_enemy','tl_marker_party_glow','tl_marker_enemy_glow','tl_flag_skill','gauge_frame','gauge_hp_track','gauge_skill_track','gauge_skill_ready'];
const im={};await Promise.all([...names.map(n=>[n,'../kit/battle/'+n+'.png']),...['bust0','bust1','bust2','boar'].map(n=>[n,'../sources/reused/'+n+'.png'])].map(async([n,src])=>{im[n]=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=src})}));await document.fonts.ready;
const draws=[];
function draw(g,n,x,y,w,h){g.drawImage(im[n],x,y,w,h);draws.push({piece:n,x,y,w,h})}
function portrait(g,n,x,y,d){g.save();g.beginPath();g.arc(x,y,d/2,0,Math.PI*2);g.clip();g.fillStyle='#102B45';g.fillRect(x-d/2,y-d/2,d,d);g.imageSmoothingEnabled=false;g.drawImage(im[n],x-d/2,y-d/2,d,d);g.restore()}
function txt(g,s,x,y,size,color='#F1E2BC'){g.save();g.textAlign='center';g.textBaseline='middle';g.font=`600 ${size}px 'Alegreya Sans'`;g.lineWidth=2;g.strokeStyle='#07131F';g.strokeText(s,x,y);g.fillStyle=color;g.fillText(s,x,y);g.restore()}
const tl=document.getElementById('tl');tl.innerHTML='';const c=document.createElement('canvas');c.width=c.height=480;tl.append(c);let g=c.getContext('2d');g.scale(2,2);g.beginPath();g.arc(120,120,112,0,Math.PI*2);g.fillStyle='rgba(7,19,31,.72)';g.fill();
for(const n of ['tl_bezel','tl_track_enemy','tl_track_party','tl_divider','tl_act_zone'])draw(g,n,0,0,240,240);
portrait(g,'bust1',120,120,60);draw(g,'tl_hub',0,0,240,240);draw(g,'tl_pointer',0,0,240,240);draw(g,'tl_act_plate',0,0,240,240);g.save();g.textAlign='center';g.textBaseline='middle';g.font="600 11px 'Cormorant Garamond'";g.fillStyle='#2A2117';g.fillText('NEXT',120,158);g.translate(77.25,120-85.5*Math.cos(Math.PI/6));g.rotate(-Math.PI/6);g.font="600 12px 'Cormorant Garamond'";g.fillText('ACT',0,0);g.restore();
for(const m of [{f:.86,n:'bust1',s:'party',acting:true},{f:.42,n:'bust0',s:'party'},{f:.16,n:'bust2',s:'party'},{f:.94,n:'boar',s:'enemy',flag:true},{f:.58,n:'boar',s:'enemy'},{f:.28,n:'boar',s:'enemy'}]){const a=(-90+m.f*300)*Math.PI/180,r=m.s==='party'?71:100,x=120+r*Math.cos(a),y=120+r*Math.sin(a);if(m.acting)draw(g,'tl_marker_'+m.s+'_glow',x-24,y-24,48,48);portrait(g,m.n,x,y,34);draw(g,'tl_marker_'+m.s,x-24,y-24,48,48);if(m.flag){draw(g,'tl_flag_skill',x-20,y-33,40,16);txt(g,'SKILL',x,y-26,8)}}
const partyData=[{nm:'Rowan',hp:142/180,sk:.55,img:'bust0'},{nm:'Aveline',hp:1,sk:1,img:'bust1'},{nm:'Mira',hp:96/150,sk:.3,img:'bust2'}];
const p=document.getElementById('party');p.innerHTML='';
for(const m of partyData){const member=document.createElement('div');member.className='member';const ring=document.createElement('div');ring.className='ring';const c=document.createElement('canvas');c.width=c.height=208;ring.append(c);member.append(ring);const tag=document.createElement('div');tag.className='tag';tag.textContent=m.nm;member.append(tag);p.append(member);const g=c.getContext('2d');g.scale(2,2);portrait(g,m.img,52,52,70);draw(g,'gauge_hp_track',0,0,104,104);draw(g,'gauge_skill_track',0,0,104,104);for(const [r,w,f,col]of [[41,9,m.hp,m.hp<.5?'#E0B04A':'#43A65E'],[49,3,m.sk,'#F08C2A']]){g.save();if(r===49&&f===1){g.shadowColor=col;g.shadowBlur=4}g.beginPath();g.arc(52,52,r,135*Math.PI/180,(135+270*f)*Math.PI/180);g.strokeStyle=col;g.lineWidth=w;g.stroke();g.restore()}draw(g,'gauge_frame',0,0,104,104);if(m.sk===1){const ready=document.createElement('span');ready.className='skillfull';ready.textContent='SKILL';ready.style.zIndex='2';ring.append(ready)}}
window.PROOF_CHECK={size:[1280,720],ring_use_size:[240,240],ring_position:[20,464],party_use_size:[104,104],all_replaced:true,draws,fonts_loaded:document.fonts.check("600 20px 'Cormorant Garamond'")&&document.fonts.check("600 15px 'Alegreya Sans'"),note:'Preserved reference HTML positioning, fixture values, background and characters. Requested 240px ring replaces original 210px placeholder.'};window.BATTLE_READY=true;
})().catch(e=>console.error(e));
