import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=f=>fs.readFileSync(root+'/'+f),json=f=>JSON.parse(read(f));
const m=json('kit.json'),qa=json('sources/qa.json');
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function png(file){const b=read(file);assert.equal(b.subarray(1,4).toString(),'PNG');const w=b.readUInt32BE(16),h=b.readUInt32BE(20),depth=b[24],type=b[25];assert.equal(depth,8);assert.ok([2,6].includes(type));const channels=type===6?4:3,parts=[];for(let p=8;p<b.length;){const n=b.readUInt32BE(p);if(b.subarray(p+4,p+8).toString()==='IDAT')parts.push(b.subarray(p+8,p+8+n));p+=n+12}const d=zlib.inflateSync(Buffer.concat(parts)),stride=w*channels,out=Buffer.alloc(w*h*channels);let p=0;for(let y=0;y<h;y++){const filter=d[p++];for(let x=0;x<stride;x++){let a=x>=channels?out[y*stride+x-channels]:0,c=y&&x>=channels?out[(y-1)*stride+x-channels]:0,u=y?out[(y-1)*stride+x]:0,v=d[p++];if(filter===1)v+=a;else if(filter===2)v+=u;else if(filter===3)v+=Math.floor((a+u)/2);else if(filter===4){const q=a+u-c,pa=Math.abs(q-a),pb=Math.abs(q-u),pc=Math.abs(q-c);v+=pa<=pb&&pa<=pc?a:pb<=pc?u:c}else assert.equal(filter,0);out[y*stride+x]=v&255}}return {w,h,data:out,channels}}
const lookup=new Map(m.pieces.map(p=>[p.piece,p]));assert.equal(lookup.size,m.pieces.length,'duplicate piece ID');
const expected={tier1:['title_ribbon_short','title_ribbon_long','clock_medallion','clock_ring','ledger_book','dialogue_name_plate','results_banner','results_row_strip','grade_s','grade_a','grade_b','grade_c','grade_d'],tier2:['card_frame_light','card_frame_heavy','header_band','header_medallion','section_heading_band','dialogue_text_box','request_client_card','request_terms_card','stamp_accepted','stamp_complete','stamp_expired','parchment_map_frame','confirm_dialog_card','battle_party_card','battle_bust_frame','attack_timer_track','attack_timer_ring','skill_meter_track','skill_meter_fill','battle_tag_front','battle_tag_back','battle_status_slot','enemy_name_banner','enemy_hp_track','enemy_hp_fill','rare_badge','battle_log_card'],tier3:['toast_info','toast_success','toast_warning','toast_critical','toast_rare','tooltip','help_ribbon','button_hint_keyboard','button_hint_gamepad','stat_plate','speed_controls','objective_row','pin_row','battle_pace','minimap_ring'],layers:['paper','watermark','stain_1','stain_2','stain_3','stain_4','stain_5','stain_6','stain_7','stain_8','corner_large_mask','corner_small_mask','diamond_row_mask','lattice_mask']};
const states=['idle','hover','pressed','disabled','selected'];
const controls=['primary_button','secondary_button','choice_button','diamond_tab','selected_row_glow','quill','hp_track','hp_fill','stat_track','stat_fill','progress_track','progress_fill','xp_track','xp_fill','stamina_segment','number_stepper','checkbox','toggle','slider','scrollbar','face_backing'];
const icons=['gold','reputation','morale','time','pause','rank_f','rank_e','rank_d','rank_c','rank_b','rank_a','rank_s','info','success','warning','critical','rare','objective','pin','hp','stamina','red_fatigue','injury','pristine','standard','damaged','unsellable','ordinary','variant','monster_rare','boss','material','corpse','equipment','consumable','recipe','adventurer_office','processing','workshop','information','commerce','guild_desk','leadership','negotiation','insight','know_how','atk_up','atk_down','def_up','def_down','slow','stun','provoke','lock','save','settings','ongoing','roster','storage','requests','bonds','journal'];
const emotes=['exclaim','question','dots','sweat','anger','laugh','heart','music','sleep','idea','sigh'];
function coverage(set=lookup){for(const [group,names]of Object.entries(expected))for(const n of names){assert.ok(set.has(n),'missing '+n);assert.equal(set.get(n).group,group)}for(const n of controls)for(const s of states)assert.ok(set.has(n+'_'+s),n+' '+s);for(const n of icons)for(const size of [24,32,48])assert.ok(set.has(n+'_'+size),n+' '+size);for(const n of emotes)assert.ok(set.has('emote_'+n),n)}
coverage();const negative=new Map(lookup);negative.delete('battle_party_card');assert.throws(()=>coverage(negative));
const dimensions={},maskResults=[];
for(const p of m.pieces){assert.match(p.file,/^kit\/[a-z0-9_]+\/[a-z0-9_]+\.png$/);assert.ok([1,2,3].includes(p.tier));assert.equal(p.margins.length,4);assert.ok(p.margins.every(n=>Number.isInteger(n)&&n>=0));const im=png(p.file);assert.deepEqual([im.w,im.h],p.size);dimensions[p.piece]=p.size;const [l,t,r,b]=p.margins;assert.ok(l+r<im.w&&t+b<im.h,'invalid margins '+p.piece);assert.equal(im.channels,4,'RGBA required');let nonempty=false,transparent=false;for(let j=0;j<im.data.length;j+=4){const a=im.data[j+3];if(a)nonempty=true;if(a<255)transparent=true;if(p.mask&&a)assert.deepEqual([...im.data.subarray(j,j+3)],[255,255,255],'nonwhite mask '+p.piece)}assert.ok(nonempty,'empty '+p.piece);if(p.mask){assert.ok(p.tint_token in m.tokens);assert.ok(transparent);maskResults.push(p.piece)}if(p.group==='icons')assert.deepEqual(p.size,[p.pixel_size,p.pixel_size]);}
for(const n of controls){const hashes=states.map(s=>hash(read(lookup.get(n+'_'+s).file)));assert.equal(new Set(hashes).size,5,'state imagery must differ '+n)}
assert.equal(qa.slice_tests.length,m.pieces.filter(p=>p.stretch).length);assert.ok(qa.slice_tests.every(p=>p.corners_identical),'nine-slice changed corner pixels');
for(const f of ['mock-dialogue','mock-battle','mock-ledger','mock-request','roster','world-hud']){const im=png('mockups/'+f+'.png');assert.deepEqual([im.w,im.h],[1920,1080]);for(let j=0;j<im.data.length;j+=im.channels)assert.ok(!(im.data[j]>220&&im.data[j+1]<70&&im.data[j+2]>220),'chroma remains '+f)}
for(const f of ['tier1','tier2','tier3','controls','icons','emotes'])assert.ok(read('sheets/'+f+'.png').length>10000);
assert.equal(m.icon_atlas.entries.length,icons.length);assert.deepEqual(m.icon_atlas.entries.map(e=>e.icon).sort(),icons.sort());png(m.icon_atlas.file);
assert.ok(qa.fonts.every(f=>f.loaded));assert.equal(m.fonts.features.lnum,1);assert.equal(m.fonts.features.onum,0);
function lum(hex){return hex.slice(1,7).match(/../g).map(n=>parseInt(n,16)/255).map(n=>n<=.04045?n/12.92:((n+.055)/1.055)**2.4).reduce((s,n,i)=>s+n*[.2126,.7152,.0722][i],0)}
const text=qa.text.filter(t=>t.screen.startsWith('mock')||['roster','world-hud'].includes(t.screen));
let minContrast=100;for(const t of text){assert.ok(t.size>=22,t.text+' too small');const ratio=t.keyline?((lum(t.color)+.05)/(lum(t.keyline)+.05)):t.minContrast;if(ratio!==null){assert.ok(ratio>=4.5,'contrast '+t.screen+' '+t.text+' '+ratio);minContrast=Math.min(minContrast,ratio)}if(/\d/.test(t.text))assert.equal(t.font,'Body','numeral font '+t.text);const left=t.align==='right'?t.x-t.width:t.align==='center'?t.x-t.width/2:t.x;assert.ok(left>=0&&left+t.width<=1920,'offscreen text '+t.text)}
const say=(scr,s)=>assert.ok(text.some(t=>t.screen===scr&&t.text===s),scr+' '+s);
say('mock-request','Timer began on first appearance.');say('mock-request','Due Day 5 · 14:20 (2 days remaining)');
say('mock-dialogue','“Fast as usual.”');say('mock-dialogue','Mae');say('roster','ADVENTURER DOSSIER');say('roster','ADVENTURERS');say('mock-request','25 G');say('mock-request','100 Rep');say('mock-request','2 Slime Cores');
const battle=qa.draws.filter(d=>d.screen==='mock-battle');const party=battle.filter(d=>d.piece==='battle_party_card');assert.equal(party.length,4);assert.ok(party.every(d=>d.x>=1390));assert.equal(battle.filter(d=>d.piece==='enemy_hp_track').length,2);assert.ok(battle.find(d=>d.piece==='battle_log_card').x<100);assert.ok(battle.some(d=>d.piece==='attack_timer_ring'));assert.ok(battle.some(d=>d.piece==='skill_meter_fill'));assert.equal(m.tokens.warning,'#D79A2B');
const ledger=qa.draws.filter(d=>d.screen==='mock-ledger');assert.ok(ledger.some(d=>d.piece==='ledger_highlight_hover'));assert.ok(ledger.some(d=>d.piece==='ledger_highlight_selected'));say('mock-ledger','!');
assert.equal(qa.sprite_crops.filter(p=>p.front).length,4);assert.ok(qa.sprite_crops.every(p=>p.nearest&&Number.isInteger(p.scale)));
const provenance=json('sources/provenance.json');for(const p of provenance){assert.equal(hash(read(p.file)),p.sha256);assert.equal(hash(fs.readFileSync(p.source)),p.sha256,'source changed '+p.source)}
const gdd=fs.readFileSync('D:/Storyboards/Isekai Mercenary Company/Game Design/IMC GDD.md','utf8'),scene=fs.readFileSync('D:/Storyboards/Isekai Mercenary Company/Manuscript/Chapter 1 - New Beginning/Scene 2 - Tavern Talk.md','utf8');assert.ok(scene.includes('"Fast as usual."'));assert.match(gdd,/Rare Slime Order[^\n]+2 Slime Cores[^\n]+25 \/ 100/);for(const c of Object.values(m.tokens))assert.ok(gdd.includes(c),'not a GDD token '+c);
const result={status:'passed',registered_pieces:m.pieces.length,icons:icons.length,icon_files:icons.length*3,controls:controls.length,control_state_files:controls.length*5,emotes:emotes.length,nine_slice_tests:qa.slice_tests.length,white_alpha_masks:maskResults.length,proof_mockups:6,required_sheets:6,extra_layer_sheet:1,minimum_measured_text_contrast:minContrast,source_hashes_verified:provenance.length,negative_control:'Missing battle_party_card rejected',limitations:['Static artwork/layout verification, no Godot runtime integration','Input bindings and transient quantities in mockups are visual fixtures']};fs.writeFileSync(root+'/sources/verification.json',JSON.stringify(result,null,2));console.log('KIT_VERIFIED',JSON.stringify(result));
